import React from "react";

export type StructuredAnnualPlanDocument = {
  schema_version: 1; resource_type: "annual_plan"; title: string; subject?: string | null; level?: string | null; class_context?: string | null; academic_year: string;
  planning_basis: string[]; calendar_constraints: string[]; course_map: Array<{ dates: string; start_date: string; end_date: string; topic: string; learning_focus: string; practical_or_assessment?: string | null; lessons: number; minutes: number }>;
  teaching_assessment_rhythm: string[]; practical_project_programme: string[]; checkpoints_and_buffers: string[]; planning_sources: string[]; assumptions_and_adjustment_rules: string[]; first_lesson?: string | null;
};
export function isStructuredAnnualPlanDocument(value: unknown): value is StructuredAnnualPlanDocument {
  const plan = value as Partial<StructuredAnnualPlanDocument> | null;
  return !!plan && plan.schema_version === 1 && plan.resource_type === "annual_plan" && typeof plan.title === "string" && Array.isArray(plan.course_map);
}
const List = ({ items }: { items: string[] }) => items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-slate-700">{items.map((item) => <li key={item}>{item}</li>)}</ul> : null;
export default function StructuredAnnualPlanPreview({ document, footer }: { document: StructuredAnnualPlanDocument; footer: string }) {
  return <article className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_20px_50px_rgba(15,23,42,0.08)]"><header className="border-b border-slate-200 bg-[linear-gradient(180deg,#ffffff,#f4fbf9)] px-6 py-6 sm:px-8"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-700">Elume annual plan</div><h1 className="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">{document.title}</h1><div className="mt-3 flex flex-wrap gap-2">{[document.subject, document.level, document.class_context, document.academic_year].filter(Boolean).map((item) => <span key={item} className="rounded-full border border-emerald-100 bg-white px-3 py-1 text-xs font-semibold text-slate-600">{item}</span>)}</div></header><div className="space-y-7 px-6 py-6 sm:px-8"><section><h2 className="text-sm font-black uppercase tracking-[0.14em] text-slate-700">Planning basis</h2><List items={document.planning_basis} /></section><section><h2 className="text-sm font-black uppercase tracking-[0.14em] text-slate-700">Calendar constraints</h2><List items={document.calendar_constraints} /></section><section><h2 className="text-sm font-black uppercase tracking-[0.14em] text-slate-700">Term by term course map</h2><div className="mt-3 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-teal-800 text-white"><tr>{["Dates", "Topic / chapter", "Learning focus", "Practical / assessment evidence"].map((heading) => <th key={heading} className="px-3 py-3 font-bold">{heading}</th>)}</tr></thead><tbody>{document.course_map.map((row, index) => <tr key={`${row.topic}-${index}`} className="border-t border-slate-200 align-top"><td className="px-3 py-3 font-semibold text-teal-800">{row.dates}</td><td className="px-3 py-3 font-bold text-slate-900">{row.topic}</td><td className="px-3 py-3 text-slate-700">{row.learning_focus}</td><td className="px-3 py-3 text-slate-700">{row.practical_or_assessment || "—"}</td></tr>)}</tbody></table></div></section>{[["Teaching and assessment rhythm", document.teaching_assessment_rhythm], ["Practical or project programme", document.practical_project_programme], ["Progress checkpoints revision and recovery buffers", document.checkpoints_and_buffers], ["Planning sources", document.planning_sources], ["Assumptions and adjustment rules", document.assumptions_and_adjustment_rules]].map(([heading, items]) => <section key={heading as string}><h2 className="text-sm font-black uppercase tracking-[0.14em] text-slate-700">{heading as string}</h2><List items={items as string[]} /></section>)}{document.first_lesson && <section><h2 className="text-sm font-black uppercase tracking-[0.14em] text-slate-700">Optional detailed first lesson</h2><p className="mt-2 text-sm leading-7 text-slate-700">{document.first_lesson}</p></section>}</div><footer className="border-t border-slate-200 bg-slate-50 px-6 py-3 text-xs text-slate-500 sm:px-8">{footer}</footer></article>;
}
