-- School Admin invitations for PostgreSQL.
-- Apply manually after 20260822_001_school_admin_foundation.up.sql.
-- This migration is intentionally not run by application startup.

BEGIN;

CREATE TABLE school_invitations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id INTEGER NOT NULL,
    normalized_email VARCHAR(320) NOT NULL,
    intended_role VARCHAR(32) NOT NULL DEFAULT 'teacher',
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITHOUT TIME ZONE NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE NULL,
    invited_by_user_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_school_invitations_intended_role CHECK (intended_role = 'teacher'),
    CONSTRAINT uq_school_invitations_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_school_invitations_school_id
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT fk_school_invitations_invited_by_user_id
        FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX ix_school_invitations_school_id ON school_invitations (school_id);
CREATE INDEX ix_school_invitations_normalized_email ON school_invitations (normalized_email);

-- One non-revoked, unaccepted invitation is allowed per school/email. Expired
-- invitations are explicitly revoked by the API before a replacement is created.
CREATE UNIQUE INDEX uq_school_invitations_open_school_email
    ON school_invitations (school_id, normalized_email)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

COMMIT;
