-- School Admin audit log for PostgreSQL.
-- Apply manually after the School Admin foundation and invitation migrations.
-- This migration is intentionally not run by application startup.

BEGIN;

CREATE TABLE school_admin_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id INTEGER NOT NULL,
    actor_user_id INTEGER NOT NULL,
    target_user_id INTEGER NULL,
    invitation_id INTEGER NULL,
    action VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_school_admin_audit_log_action CHECK (
        action IN (
            'invitation_created',
            'invitation_resent',
            'invitation_revoked',
            'invitation_accepted',
            'teacher_deactivated',
            'teacher_reactivated'
        )
    ),
    CONSTRAINT fk_school_admin_audit_log_school_id
        FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT,
    CONSTRAINT fk_school_admin_audit_log_actor_user_id
        FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_school_admin_audit_log_target_user_id
        FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_school_admin_audit_log_invitation_id
        FOREIGN KEY (invitation_id) REFERENCES school_invitations(id) ON DELETE RESTRICT
);

CREATE INDEX ix_school_admin_audit_log_school_created_at
    ON school_admin_audit_log (school_id, created_at DESC);
CREATE INDEX ix_school_admin_audit_log_actor_user_id
    ON school_admin_audit_log (actor_user_id);
CREATE INDEX ix_school_admin_audit_log_target_user_id
    ON school_admin_audit_log (target_user_id);
CREATE INDEX ix_school_admin_audit_log_invitation_id
    ON school_admin_audit_log (invitation_id);

COMMIT;
