-- School Admin foundation for PostgreSQL.
-- Apply manually after taking and verifying an AWS RDS snapshot.
-- This migration is intentionally not run by application startup.

BEGIN;

CREATE TABLE schools (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    seat_limit INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_schools_status
        CHECK (status IN ('active', 'suspended', 'inactive')),
    CONSTRAINT ck_schools_seat_limit_nonnegative
        CHECK (seat_limit >= 0)
);

ALTER TABLE users
    ADD COLUMN role VARCHAR(32),
    ADD COLUMN school_id INTEGER,
    ADD COLUMN is_active BOOLEAN;

UPDATE users
SET
    role = 'teacher',
    is_active = TRUE
WHERE role IS NULL OR is_active IS NULL;

-- Preserve the existing hard-coded super-admin behaviour during transition.
UPDATE users
SET role = 'platform_admin'
WHERE lower(email) = 'admin@elume.ie';

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'teacher',
    ALTER COLUMN role SET NOT NULL,
    ALTER COLUMN is_active SET DEFAULT TRUE,
    ALTER COLUMN is_active SET NOT NULL,
    ADD CONSTRAINT ck_users_role
        CHECK (role IN ('teacher', 'school_admin', 'platform_admin')),
    ADD CONSTRAINT fk_users_school_id
        FOREIGN KEY (school_id)
        REFERENCES schools(id)
        ON DELETE RESTRICT;

CREATE INDEX ix_users_school_id ON users (school_id);

COMMIT;
