import React, { useEffect, useState } from "react";
import { ArrowDownToLine, ChevronLeft, FileText } from "lucide-react";

type Item={id:string;title:string;cycle:string;level:string;topic:string;duration:string;marks:string;badge?:string;download_filename:string};
type Collection={id:string;title:string;description:string;items:Item[]};
const collectionId="mr-fitz-maths-mini-papers";
export default function PublicExamCollectionPage(){
 const [data,setData]=useState<Collection|null>(null); const [error,setError]=useState(false);
 useEffect(()=>{fetch(`/api/public-exam-collections/${collectionId}`,{credentials:"omit"}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setError(true));},[]);
 return <main className="min-h-screen bg-slate-50 px-4 py-7 text-slate-900 sm:px-6"><div className="mx-auto max-w-4xl"><a href="/#/student/exam-papers" className="inline-flex items-center gap-1 rounded-xl px-2 py-2 font-bold text-slate-600"><ChevronLeft size={18}/> Examination Papers</a><section className="mt-4 rounded-[32px] border border-teal-100 bg-white p-6 shadow-xl shadow-teal-100/50 sm:p-8"><div className="inline-flex rounded-2xl bg-teal-100 p-3 text-teal-800"><FileText size={28}/></div><p className="mt-4 text-sm font-black uppercase tracking-wide text-teal-700">Original practice material</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{data?.title||"Mr Fitz Maths Mini Papers"}</h1><p className="mt-3 max-w-2xl leading-6 text-slate-600">{data?.description||"Loading the collection…"}</p>{error?<div className="mt-6 rounded-2xl bg-red-50 p-5 font-bold text-red-800">This collection is unavailable right now. Please try again later.</div>:!data?<div className="mt-6 rounded-2xl bg-slate-50 p-5 text-slate-600">Loading papers…</div>:<div className="mt-6 space-y-3">{data.items.map((item,index)=><article key={item.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-black">{item.title}</h2>{item.badge&&<span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-800">{item.badge}</span>}</div><p className="mt-2 text-sm text-slate-600">{item.cycle} · {item.level} · {item.topic} · {item.duration} · {item.marks}</p></div><a download={item.download_filename} href={`/api/public-exam-collections/${collectionId}/items/${item.id}/download`} className="inline-flex min-h-[48px] items-center justify-center gap-2 rounded-xl bg-teal-700 px-4 font-black text-white"><ArrowDownToLine size={18}/> Open / download</a></article>)}</div>}</section></div></main>
}
