import React, { useEffect, useState } from "react";
import { ArrowDownToLine, ChevronRight, FileText, Folder } from "lucide-react";
import { useParams } from "react-router-dom";

type Paper = { id:string; title:string; cycle:string; level:string; level_id:string; topic:string; topic_id:string; duration:string; marks:string; badge?:string; download_filename:string };
type Topic = { id:string; level_id:string; title:string; published_paper_count:number };
type Level = { id:string; title:string; published_paper_count:number };
type Collection = { title:string; levels:Level[]; topics:Topic[]; items:Paper[] };
const id = "mr-fitz-maths-mini-papers";
function useCollection(){const [data,setData]=useState<Collection|null>(null);const [error,setError]=useState(false);useEffect(()=>{let cancelled=false;fetch(`/api/public-exam-collections/${id}`,{credentials:"omit"}).then(r=>r.ok?r.json():Promise.reject()).then(x=>!cancelled&&setData(x)).catch(()=>!cancelled&&setError(true));return()=>{cancelled=true};},[]);return{data,error}}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-slate-50 px-4 py-7 text-slate-900 sm:px-6"><div className="mx-auto max-w-4xl">{children}</div></main>}
function Crumbs({level,topic}:{level?:string;topic?:string}){return <nav aria-label="Breadcrumb" className="mb-4 flex flex-wrap items-center gap-1 text-sm font-bold text-slate-600"><a href="/#/student/exam-papers">Exam Papers</a><ChevronRight size={16}/><a href={`/#/student/exam-papers/${id}`}>Mr Fitz Maths Mini Papers</a>{level&&<><ChevronRight size={16}/><span>{level}</span></>}{topic&&<><ChevronRight size={16}/><span>{topic}</span></>}</nav>}
const Card=({href,title,count}:{href:string;title:string;count:number})=><a href={href} className="flex min-h-[92px] items-center justify-between rounded-2xl border border-slate-200 p-5 hover:border-teal-300 hover:bg-teal-50 focus:outline-none focus:ring-4 focus:ring-teal-200"><span className="flex items-center gap-4"><span className="rounded-xl bg-teal-100 p-3 text-teal-700"><Folder aria-hidden="true"/></span><span><b className="block text-lg">{title}</b><span className="text-sm text-slate-600">{count} published papers</span></span></span><ChevronRight aria-hidden="true"/></a>;
export default function PublicExamCollectionPage(){const{data,error}=useCollection();return <Shell><Crumbs/>{error?<p>Collection unavailable.</p>:!data?<p>Loading collection...</p>:<section className="rounded-[32px] border border-teal-100 bg-white p-6"><FileText className="text-teal-700"/><p className="mt-4 text-sm font-black text-teal-700">ORIGINAL PRACTICE MATERIAL</p><h1 className="text-3xl font-black">{data.title}</h1><div className="mt-6 space-y-3">{data.levels.map(x=><Card key={x.id} href={`/#/student/exam-papers/${id}/${x.id}`} title={x.title} count={x.published_paper_count}/>)}</div></section>}</Shell>}
export function PublicExamLevelPage(){const{levelId=""}=useParams();const{data,error}=useCollection();const level=data?.levels.find(x=>x.id===levelId);return <Shell><Crumbs level={level?.title}/>{error||data&&!level?<p>Level unavailable.</p>:!data?<p>Loading topics...</p>:<section className="rounded-[32px] border border-teal-100 bg-white p-6"><h1 className="text-3xl font-black">{level?.title}</h1><div className="mt-6 space-y-3">{data.topics.filter(x=>x.level_id===levelId).map(x=><Card key={x.id} href={`/#/student/exam-papers/${id}/${levelId}/${x.id}`} title={x.title} count={x.published_paper_count}/>)}</div></section>}</Shell>}
export function PublicExamTopicPage({legacyTopicId}:{legacyTopicId?:string}){const p=useParams();const levelId=p.levelId||"leaving-cert-higher-level";const topicId=legacyTopicId||p.topicId||"";const{data,error}=useCollection();const topic=data?.topics.find(x=>x.id===topicId&&x.level_id===levelId);const papers=data?.items.filter(x=>x.topic_id===topicId&&x.level_id===levelId)||[];return <Shell><Crumbs level={data?.levels.find(x=>x.id===levelId)?.title} topic={topic?.title}/>{error||data&&!topic?<p>Topic unavailable.</p>:!data?<p>Loading papers...</p>:<section className="rounded-[32px] border border-teal-100 bg-white p-6"><h1 className="text-3xl font-black">{topic?.title}</h1><div className="mt-6 space-y-3">{papers.map(x=><article key={x.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex gap-2"><h2 className="font-black">{x.title}</h2>{x.badge&&<span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-800">{x.badge}</span>}</div><p className="mt-2 text-sm text-slate-600">{x.cycle} | {x.level} | {x.topic} | {x.duration} | {x.marks}</p></div><a download={x.download_filename} href={`/api/public-exam-collections/${id}/items/${x.id}/download`} className="inline-flex min-h-[48px] items-center gap-2 rounded-xl bg-teal-700 px-4 font-black text-white"><ArrowDownToLine/>Open / download</a></article>)}</div></section>}</Shell>}
